title: Choir Directory
description: A directory of choirs in my region
theme: minima

# GitHub Pages supports a limited set of plugins
plugins:
  - jekyll-seo-tag  # ✅ This one is safe

collections:
  choirs:
    output: true
  concerts:
    output: true
    permalink: /:name/
